### ISSUE TITLE
RuntimeError: The size of tensor

### ISSUE THREAD

**Issue by AnanthuAjay** [tinkerhub-org/ComputerVision-with-PyTorch-Learning-Program#12]
> This runtime error is showing up
Could you plz help me with it?
## OS, package manager and PyTorch Version
* OS -Windows
* PyTorch Version -Stable (1.5)
* Package Manager -Pip

## Complete Error Log
````
python day2.py
Traceback (most recent call last):
  File "day2.py", line 12, in <module>
    t=torch.mul(a,b)
RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1
```

**Comment by Harikrishnan6336** [comment]
`torch.mul`  is performing **element-wise multiplication,** where both the matrices need to have the same shape.

In Order to perform matrix multiplication you need to use either `torch.mm()` or `torch.matmul()`
