### ISSUE TITLE
import torch shows error

### ISSUE THREAD

**Issue by LijaAlex12** [tinkerhub-org/ComputerVision-with-PyTorch-Learning-Program#6]
> pytorch was installed successfully but the import pytorch command throws me error
## OS, package manager and PyTorch Version

* OS -macOS catalina
* PyTorch Version -Stable(1.5)
* Package Manager -pip
* python 3.8

tried the command brew install libomp
## Complete Error Log
```
> Successfully installed future-0.18.2 numpy-1.18.5 pillow-7.1.2 torch-1.5.0 torchvision-0.6.0
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
lijaalex@Lijas-MBP ~ % python3
Python 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()
lijaalex@Lijas-MBP ~ % python3
Python 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/__init__.py", line 136, in <module>
    from torch._C import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/_C.cpython-38-darwin.so, 2): Library not loaded: @rpath/libc++.1.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/_C.cpython-38-darwin.so
  Reason: image not found
```

**Comment by gksoriginals** [comment]
@LijaAlex12 can you try running the following command in terminal ?
```
cp /Library/Frameworks/Python.framework/Versions/3.8/lib/libc++.1.dylib venv/lib/python3.8/site-packages/torch/lib
```

**Comment by LijaAlex12** [comment]
## cp /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/lib

```
lijaalex@Lijas-MBP torch % cd lib\ copy 
lijaalex@Lijas-MBP lib copy % ls
libc10.dylib				libcaffe2_observers.dylib		libtorch_cpu.dylib
libcaffe2_detectron_ops.dylib		libshm.dylib				libtorch_global_deps.dylib
libcaffe2_module_test_dynamic.dylib	libtorch.dylib				libtorch_python.dylib
lijaalex@Lijas-MBP lib copy % 
```

**Comment by gksoriginals** [comment]
@psbots @kurianbenoy  any ideas how to fix this ?

**Comment by AnanthuAjay** [comment]
> PyTorch was installed successfully but the import PyTorch command throws me an error

**Complete Log**

```C:\And\learning\ComputerVision-with-PyTorch-Learning-Program\tasks>python day2.py
Traceback (most recent call last):
  File "day2.py", line 4, in <module>
    import torch
  File "C:\Users\DELL\Anaconda3\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Users\DELL\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by gksoriginals** [comment]
@AnanthuAjay could you check your python path in the windows machine ?

**Comment by ShivaniSSS** [comment]
I have the same error as @AnanthuAjay and I tried adding Anaconda's path in the edit environment variables settings, but there's no change.

**Comment by AnanthuAjay** [comment]
````
where` python
C:\Users\DELL\Anaconda3\python.exe
C:\Users\DELL\.windows-build-tools\python27\python.exe
C:\Users\DELL\AppData\Local\Microsoft\WindowsApps\python.exe
````

**Comment by LijaAlex12** [comment]
### issue resolved [https://github.com/tinkerhub-org/ComputerVision-with-PyTorch-Learning-Program/issues/6#issue-633444991]

> > pytorch was installed successfully but the import pytorch command throws me error


> ## OS, package manager and PyTorch Version
> * OS -macOS catalina
> * PyTorch Version -Stable(1.5)
> * Package Manager -pip
> * python 3.8
> 
> tried the command brew install libomp
> 
> ## Complete Error Log
> ```
> > Successfully installed future-0.18.2 numpy-1.18.5 pillow-7.1.2 torch-1.5.0 torchvision-0.6.0
> WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> lijaalex@Lijas-MBP ~ % python3
> Python 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) 
> [Clang 6.0 (clang-600.0.57)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> exit
> Use exit() or Ctrl-D (i.e. EOF) to exit
> >>> exit()
> lijaalex@Lijas-MBP ~ % python3
> Python 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) 
> [Clang 6.0 (clang-600.0.57)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/__init__.py", line 136, in <module>
>     from torch._C import *
> ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/_C.cpython-38-darwin.so, 2): Library not loaded: @rpath/libc++.1.dylib
>   Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/_C.cpython-38-darwin.so
>   Reason: image not found
> ```

**related to import torch error**
* [https://github.com/tinkerhub-org/ComputerVision-with-PyTorch-Learning-Program/issues/6#issue-633444991]

` cp /usr/lib/libc++.1.dylib /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/lib/`

* copy libc++.1.dylib to the lib folder in Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/

* this would resolve the issue

```
>>> import torch
>>> x=torch.rand(5,3)
>>> x
tensor([[0.6089, 0.7844, 0.4532],
        [0.4332, 0.9495, 0.4486],
        [0.1580, 0.6560, 0.4819],
        [0.1580, 0.4953, 0.8705],
        [0.1051, 0.1768, 0.3085]])
```
