### ISSUE TITLE
RuntimeError while doing Task 4

### ISSUE THREAD

**Issue by AnanthuAjay** [tinkerhub-org/ComputerVision-with-PyTorch-Learning-Program#80]
## Specific Question
> Could you help me out with this
## OS, package manager and PyTorch Version
> Add the following details.
* OS -Windows
* PyTorch Version -1.5
* Package Manager -pip

## Complete Error Log

```
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by gksoriginals** [comment]
@AnanthuAjay can you show me the code as well ?

**Comment by Harikrishnan6336** [comment]
Wrapping the whole code ([cifar10cnn.py](https://github.com/tinkerhub-org/ComputerVision-with-PyTorch-Learning-Program/blob/master/resources/cifar10cnn.py)) except the import statements inside  

`if __name__ == '__main__':`     resolved the issue for me

Refer [here](https://stackoverflow.com/questions/50701690/pytorch-tutorial-error-training-a-classifier)

**Comment by Harikrishnan6336** [comment]
Just found another solution also,
 
Just change the value of num_worker of torch.utils.data.DataLoader() to 0. (currently it is 2)

This is some issue specific to Windows OS and is mentioned in the [tutorial](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html)

**Comment by AnanthuAjay** [comment]
Thank you guys!!
